#GlobalChatting Configuration.

#mute the global chat so no one can talk. (only the player that has the permission can talk)
is-muted: false

globalchat:
  default:

    #permission to use this channel.
    #if permission is empty, everyone can use this channel.
    permission: "globalchatting.default"

    #this is the format of the message that will be sent to the global chat.
    #placeholder: {player}, {message}, {server}, {time}, {date}.
    #if format is empty, it will use the default format of plugin has.
    format: "&8[&7{date}, {time}&8] &8[&aGlobal&8] &r{player}&7: &r{message}"

    #this settings make you whether use color or not.
    #if you leave this empty or not set this, it will return false.
    useColor: false

    #this setting will determine which one will be selected first.
    #the higher number will be chosen first.
    #if you leave this empty or not set this, it will return 0.
    priority: 1

    #this setting will cooldown the message that you send to the global chat.
    #if you want to disable this, set this to 0.
    cooldown: 60

  staff:
    permission: "globalchatting.staff"
    format: "&8[&7{date}, {time}&8] &8[&aGlobal&8] &8[&bStaff&8] &r{player}&7: &r{message}"
    useColor: true
    priority: 5
    cooldown: 0