# GlobalChatting Configuration.

# mute the global chat so no one can talk. (only the player that has the permission can talk)
# Permission to bypass mute: globalchatting.bypass-muted
is-muted: false

# cooldown the player when they first time played on the server.
# note that these settings will not work if your not install LuckPerms BungeeCord.
# you may install LuckPerms on your BungeeCord first.
cooldown-on-first-login: true

# cooldown time for player when they first time played on the server.
first-login-cooldown: 300

# add your blacklisted server here.
# this will deny player that using global chat from server listed here.
blacklist-server:
  - "blacklist"
  - "your-server-here"
  - "from-using-globalchat"

# message that will send to player when try to use global chat from blacklisted server
blacklist-server-message: "&cYou can't use global chat in this server!"

# group your server so when the server name is called, it will return the group name.
# this feature will replace {server} placeholder and replace it with group name,
# also this feature only for player format, not console format.
#
# e.g.
# server-groups:
#   <group_name>:
#     - <server_here>
#     - <another_server>
server-groups:
  example:
    - your-server-here
    - server-to-group
  test:
    - server1
    - server2

console:
  # this settings will set the {player} placeholder.
  name: "CONSOLE"

  # this settings will set the {server} placeholder.
  server: "Proxy"

  # this is the format of the message that will be sent to the global chat.
  # placeholder: {player}, {message}, {server}, {time}, {date}.
  format: "&8[&7{date}, {time}&8] &8[&aGlobal&8] &8[&e{server}&8] &r{player}&7: &r{message}"

globalchat:
  default:

    # permission to use this channel.
    # if permission is empty, everyone can use this channel.
    permission: "globalchatting.default"

    # this is the format of the message that will be sent to the global chat.
    # placeholder: {player}, {message}, {server}, {time}, {date}, {luckperms_prefix}, {luckperms_suffix}.
    # if format is empty, it will use the default format of plugin has.
    format: "&8[&7{date}, {time}&8] &8[&aGlobal&8] &8[&e{server}&8] &r{player}&7: &r{message}"

    # this settings make you whether you use color or not.
    # if you leave this empty or not set this, it will return false.
    useColor: false

    # this settings make you whether you use hex color or not (if you enable this, useColor will turn to true).
    # if you leave this empty or not set this, it will return false.
    useHexColor: false

    # this setting will determine which one will be selected first.
    # the higher number will be chosen first.
    # if you leave this empty or not set this, it will return 0.
    priority: 1

    # set the cooldown for message that you send to the global chat.
    # if you want to disable this, set this to 0.
    cooldown: 60

  staff:
    permission: "globalchatting.staff"
    format: "&8[&7{date}, {time}&8] &8[&aGlobal&8] &8[&e{server}&8] &8[&bStaff&8] &r{player}&7: &r{message}"
    useColor: true
    useHexColor: true
    priority: 5
    cooldown: 0